sonar.projectKey=UNIZAR-30248-2026-TRAVELWRAP_Frontend
sonar.organization=unizar-30248-2026-travelwrap

# Indicar la carpeta del código fuente a analizar
sonar.sources=Frontend/src

# Excluir carpetas no relevantes para el análisis de código
sonar.exclusions=node_modules/**, dist/**, tests_cucumber/**

# Codificación
sonar.sourceEncoding=UTF-8